=== Naderi14/DAM/LLENGUATGE DE MARQUES/RA1/DTD/AC01/AC01_Exercici5.dtd
<!ELEMENT team ((player+, trainer+)*)>
<!ELEMENT player (name, lastname, height?, position*)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT lastname (#PCDATA)>
<!ELEMENT height (#PCDATA)>
<!ELEMENT position (#PCDATA)>
<!ELEMENT trainer EMPTY>
<!ATTLIST player code ID #REQUIRED>
<!ATTLIST trainer name CDATA #REQUIRED>
<!ATTLIST trainer players IDREFS #IMPLIED>

=== Naderi14/DAM/LLENGUATGE DE MARQUES/RA1 + RA4/DTD/AC01/AC01_Exercici5.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE team SYSTEM "AC01_Exercici5.dtd">

<team>
    <player code="P1">
        <name>Homer</name>
        <lastname>Simpson</lastname>
        <height>1.85</height>
        <position>Goal Kepper</position>
        <position>Defender</position>
    </player>
    <player code="P2">
        <name>Bart</name>
        <lastname>Simpson</lastname>
        <height>1.55</height>
        <position>Forward</position>
    </player>
    <player code="P3">
        <name>Lisa</name>
        <lastname>Simpson</lastname>
        <height>1.45</height>
        <position>Goal Kepper</position>
        <position>Defender</position>
    </player>
    <player code="P4">
        <name>Maggie</name>
        <lastname>Simpson</lastname>
        <position>Midfielder</position>
        <position>Defender</position>
    </player>
    <trainer name="Trainer1" players="P1 P2"/>
    <trainer name="Trainer2" players="P1 P3 P4"/>
</team>
