=== Naderi14/DAM/LLENGUATGE DE MARQUES/RA1/DTD/AC01/AC01_Exercici1.dtd
<!ELEMENT biblioteca (llibre*)>
<!ELEMENT llibre (autor+, titol, isbn?,estat)>
<!ELEMENT autor (nom, cognom+)>
<!ELEMENT nom (#PCDATA)>
<!ELEMENT cognom (#PCDATA)>
<!ELEMENT titol (#PCDATA)>
<!ELEMENT estat EMPTY>
<!ELEMENT isbn (#PCDATA)>
<!ATTLIST llibre cod ID #REQUIRED>
<!ATTLIST estat prestado CDATA "No">

=== Naderi14/DAM/LLENGUATGE DE MARQUES/RA1/DTD/AC01_Exercici1.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE biblioteca SYSTEM "AC01_Exercici1.dtd">
<biblioteca>
    <llibre cod="A0001">
        <autor>
            <nom>Jonh Palmer</nom>
            <cognom>Brian</cognom>
        </autor>
        <titol>XML en 24 horas</titol>
        <estat prestado=""/>
    </llibre>
    <llibre cod="A0002">
        <autor>
            <nom>Juan Ramón</nom>
            <cognom>López</cognom>
            <cognom>Prats</cognom>
        </autor>
        <titol>XML en 48 horas</titol>
        <isbn>8-12345-09</isbn>
        <estat prestado="Si"/>
    </llibre>
</biblioteca>
