=== Naderi14/DAM/LLENGUATGE DE MARQUES/RA1 + RA4/DTD/AC01/AC01_Exercici2.dtd
<!ELEMENT temps (entitat)>
<!ELEMENT entitat (nom, ubicacio, prediccio)>
<!ELEMENT nom (#PCDATA)>
<!ELEMENT ubicacio (ciutat, provincia)>
<!ELEMENT ciutat (#PCDATA)>
<!ELEMENT provincia (#PCDATA)>
<!ELEMENT prediccio (precipitacio, vent)>
<!ELEMENT precipitacio (#PCDATA)>
<!ELEMENT vent (direccio, velocitat)>
<!ELEMENT direccio (#PCDATA)>
<!ELEMENT velocitat (#PCDATA)>
<!ATTLIST entitat id ID #REQUIRED>
<!ATTLIST prediccio data CDATA #REQUIRED>

=== Naderi14/DAM/LLENGUATGE DE MARQUES/RA1/DTD/AC01/AC01_Exercici2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE temps SYSTEM "AC01_Exercici2.dtd">
<temps>
    <entitat id="AZ000000A">
        <nom>Agencia Santbolana de meteorologia</nom>
        <ubicacio>
            <ciutat>Sant Boi</ciutat>
            <provincia>Barcelona</provincia>
        </ubicacio>
        <prediccio data="2011-12-20">
            <precipitacio>14</precipitacio>
            <vent>
                <direccio>NE</direccio>
                <velocitat>77</velocitat>
            </vent>
        </prediccio>
    </entitat>
</temps>
